import java_cup.runtime.*;

parser code {:
  public static void main(String[] args) throws Exception {
    Compilador.main(args);
  }
:}

terminal LT, GT, LTSLASH, SLASHGT, EQ;
terminal String ID, STRING;

non terminal html, tag, attr_list, attr, content;

start with html;

html ::= tag
       | tag html
       ;

tag ::= LT ID attr_list GT content LTSLASH ID GT
     | LT ID attr_list SLASHGT
     ;

attr_list ::= /* vazio */
            | attr attr_list
            ;

attr ::= ID EQ STRING
       ;

content ::= /* vazio */
          | ID
          | STRING
          ;
