
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PTVIRG = 7;
  public static final int INTEIRO = 12;
  public static final int COLCHETEESQ = 8;
  public static final int MENOR = 6;
  public static final int COLCHETEDIR = 9;
  public static final int EOF = 0;
  public static final int PARENTESQ = 10;
  public static final int ID = 13;
  public static final int IGUAL = 5;
  public static final int error = 1;
  public static final int PARENTDIR = 11;
  public static final int INC = 4;
  public static final int DO = 2;
  public static final int OUT = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DO",
  "OUT",
  "INC",
  "IGUAL",
  "MENOR",
  "PTVIRG",
  "COLCHETEESQ",
  "COLCHETEDIR",
  "PARENTESQ",
  "PARENTDIR",
  "INTEIRO",
  "ID"
  };
}

